### ISSUE TITLE
Hello world in R 

### ISSUE THREAD

**Issue by ssghait007** [tb-rules10/Hello-World#36]
R is a programming language and software environment for statistical analysis, graphics representation and reporting

https://www.r-project.org/

**Comment by tb-rules10** [comment]
Np

**Comment by tb-rules10** [comment]
Im new i dont kno how to assign an issue

**Comment by ssghait007** [comment]
@babaiyu Also. You can create PR directly and reference this issue in PR title like `YOUR PR TITLE for #36`
